#simple_model is the name space
simple_model:
    # based on https://wiki.ros.org/ros_control this controller reads the state 
    # of all the joints
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    base_to_second_joint_position_controller:
        #this controller recieves position and via PID it takes care of the effort
        # needed to move the joint. based on https://wiki.ros.org/ros_control
        type: position_controllers/JointPositionController
        joint: base_to_second_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}
